### PR TITLE
203 SqlServer Ad Auth

### PR DESCRIPTION
**Pull request by idesai1210**
SqlServer AD Authentication issues #203

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
This looks excellent, thank you - I'll make sure we review it soon.

**Comment by idesai1210** [comment]
@Aaronontheweb Can I know how long it will take to be published it to nuget, so that I can plan my dev task accordingly?

**Review by Aaronontheweb — APPROVED** [review]
LGTM

**Comment by Aaronontheweb** [comment]
@idesai1210 I'll push a release of this today

**Pull request merged**
