### PR TITLE
Update Akka.Persistence.Sql.Common to 1.4.21-beta1

### PR DESCRIPTION
**Pull request by Arkatufus**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Excellent, thank you - wanted to validate the batching sql tests.

**Comment by Aaronontheweb** [comment]
@Arkatufus I think we can safely bring Akka.Persistence.Sql.Common out of beta

**Comment by Aaronontheweb** [comment]
cc @ismaelhamed

**Comment by ismaelhamed** [comment]
We haven't had the time to thoroughly test it, but after a couple of betas I guess that if there was any problem at all somebody would've raised some concern by now.

**Pull request closed without merging**
