### PR TITLE
Update to latest Akka.NET version 1.1.3

### PR DESCRIPTION
**Pull request by heynickc**
Updates Akka.NET dependency

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@heynickc looks like this PR was affected by some of the same issues as others on this one... Not sure what the issue is but it smells like an infrastructure issue.

**Comment by heynickc** [comment]
@Horusiath In that case, the Akka dependency can wait.  I was just getting dependencies as consistent across plugins as I could.  Still would like to use this PR to diagnose what's happening on TeamCity

**Comment by pmbanka** [comment]
@heynickc if I understand correctly, `System.Collections.Immutable` should be bumped to 1.3.1 instead of 1.2.0. See e.g.  https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/persistence/Akka.Persistence.Sql.Common/packages.config

**Comment by heynickc** [comment]
@pmbanka Thanks.  I was following a troubleshooting trail that the CI system was taking me down but yea, you're right I'll fix that.

**Comment by pmbanka** [comment]
Hi @heynickc, based on [this message](https://github.com/akkadotnet/Akka.Persistence.SqlServer/pull/60#issuecomment-286982308) I presume that this PR should be merged before the other bugfixes. Do you have any estimations when it will be ready? Is there something I can do to help with the task?

**Comment by heynickc** [comment]
Hey @pmbanka, this PR is ready to merge in terms of simply updating the Akka dependencies, making the build scripts consistent with the other plugins (and Akka), and updating System.Collections.Immutable.  The reason it's not passing CI checks is due to flaky tests, which I'd like to address ASAP.  I can reproduce locally, so it's a matter of discovering root-cause.  I think this PR can be merged, followed by fixing the test flakiness so we can trust CI, then any further bug fixes so we can start with a solid baseline in terms of CI.  What do you think?

**Comment by pmbanka** [comment]
> What do you think?

I think that anything that will make the build pass and PRs merged is good :)

**Comment by heynickc** [comment]
Closing, to be replaced by #62 and fix to other flaky tests by https://github.com/akkadotnet/akka.net/pull/2585

**Pull request closed without merging**
