### PR TITLE
Batching journal

### PR DESCRIPTION
**Pull request by Horusiath**
This PR brings an alternative version of journals introduced in v1.1.3, namely batching journals. Details included in README.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
cc @Horusiath some spec failures:

BatchingSqlServerEventsByPersistenceIdSpec.Sql_query_EventsByPersistenceId_should_return_empty_stream_for_cleaned_journal_from_0_to_MaxLong 	
 BatchingSqlServerEventsByPersistenceIdSpec.Sql_query_EventsByPersistenceId_should_return_remaining_values_after_partial_journal_cleanup

**Comment by Horusiath** [comment]
For some reason those tests fail when run all at once, but behave correctly when run one by one.

**Comment by Aaronontheweb** [comment]
@Horusiath thinking we can merge this. @heynickc Identified the issue here is that the way the Akka.Persistence.TestKit is designed makes all of these implementations vulnerable to race conditions during unit testing, in the form of "dirtying" the data between tests. Any thoughts?

**Comment by pmbanka** [comment]
@Horusiath I believe code in this PR has similar problem to one fixed by https://github.com/akkadotnet/Akka.Persistence.SqlServer/pull/60

`BatchingSqlJournal` provides a [default implementation for ByTagSql](https://github.com/akkadotnet/akka.net/blob/fcc457b3f12ab5153bbd73df65d37166b4e5c923/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs#L574) which does not use [@Take parameter passed into command](https://github.com/akkadotnet/akka.net/blob/fcc457b3f12ab5153bbd73df65d37166b4e5c923/src/contrib/persistence/Akka.Persistence.Sql.Common/Journal/BatchingSqlJournal.cs#L950).

I think that in order to fix that, `BatchingSqlServerJournal` should override `ByTagSql` and set it in constructor:

```
protected override string ByTagSql { get; }
```
```
ByTagSql =
                $@"
                SELECT TOP (@Take) 
                e.{conventions.PersistenceIdColumnName} as PersistenceId, 
                e.{conventions.SequenceNrColumnName} as SequenceNr, 
                e.{conventions.TimestampColumnName} as Timestamp, 
                e.{conventions.IsDeletedColumnName} as IsDeleted, 
                e.{conventions.ManifestColumnName} as Manifest, 
                e.{conventions.PayloadColumnName} as Payload,
                e.{conventions.OrderingColumnName} as Ordering
                FROM {conventions.FullJournalTableName} e
                WHERE e.{conventions.OrderingColumnName} > @Ordering AND e.{conventions.TagsColumnName} LIKE @Tag
                ORDER BY {conventions.OrderingColumnName} ASC";
```

**Pull request closed without merging**
