### PR TITLE
Deterministic EventJournal primary key name.

### PR DESCRIPTION
**Pull request by object**
The new Ordering primary key didn't provide explicit name for the PK constraint which resulted in non-deterministic name assignment (and will make it hard to maintain the future versions of the script). The PR provides explicit name for the primary key (PK_{your_journal_table_name}).

### CODE REVIEW

**Comment by object** [comment]
Fixed table naming.

**Comment by Horusiath** [comment]
I cannot check now why TeamCity broke, but PR is :+1:

**Comment by object** [comment]
Can not understand why TC broke either. AFAIK this change shouldn't affect anything.

**Comment by Aaronontheweb** [comment]
cc @heynickc regarding TC issues

**Comment by Horusiath** [comment]
We need to rerun the tests and merge the changes. Unfortunately I cannot do this from work.

**Comment by Danthar** [comment]
Same issue as #60 /cc @heynickc

**Comment by object** [comment]
Rebased from the lastest dev.

**Comment by object** [comment]
It complains "Could not install package 'System.Threading.Timer 4.3.0".

**Comment by heynickc** [comment]
@object, @Danthar, @Horusiath... #69 resolves this and #60.  We're not going to see the build pass on Mono until I fix #70 but we also can't run tests on Mono yet since we're locked into Docker for Windows.  I have paused the Mono Build step on TeamCity until then, but you might see red x's on existing PRs.

**Comment by Danthar** [comment]
I merged #69.
@object If you update to the latest again it should be fixed.

**Comment by object** [comment]
Updated to the latest.

**Pull request merged**
