### PR TITLE
Enable Serialization Specs

### PR DESCRIPTION
**Pull request by heynickc**
Turns on Serialization Specs and also updates build script to use `dotnet xunit` instead of `dotnet test`

### CODE REVIEW

**Comment by heynickc** [comment]
this also addresses #79 "Run .NET Core specs in build.fsx"

**Comment by Aaronontheweb** [comment]
@heynickc need to resolve conflicts

**Comment by heynickc** [comment]
@Aaronontheweb they are resolved now

**Comment by alexvaluyskiy** [comment]
@Aaronontheweb @heynickc If we have a batching journal, we should implement `SerializationSpec` for it too.

**Pull request merged**
